/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pertemuan11_guilanjutan;

import java.awt.Font;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import Models.Book;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
/**
 *
 * @author irzir
 */
public class BookPage extends javax.swing.JPanel {

    private JTable table;
    private DefaultTableModel model;


    public BookPage(MainFrame frame) {
        setLayout(null);
        
        
        // ####### Ini tampilan saja
        JLabel title = new JLabel("Daftar Buku");
        title.setFont(new Font("Segoe UI", Font.BOLD, 18));
        title.setBounds(260, 20, 200, 30);
        add(title);

        model = new DefaultTableModel(new Object[]{"Judul", "Penulis", "Tahun"}, 0);
        table = new JTable(model);
        JScrollPane scrollPane = new JScrollPane(table);
        scrollPane.setBounds(100, 70, 500, 200);
        add(scrollPane);

        JButton btnAdd = new JButton("Tambah");
        JButton btnEdit = new JButton("Edit");
        JButton btnDelete = new JButton("Hapus");
        JButton btnBack = new JButton("Kembali");

        btnAdd.setBounds(100, 290, 100, 30);
        btnEdit.setBounds(210, 290, 100, 30);
        btnDelete.setBounds(320, 290, 100, 30);
        btnBack.setBounds(500, 290, 100, 30);

        add(btnAdd);
        add(btnEdit);
        add(btnDelete);
        add(btnBack);
        
        /// ##############

//        btnAdd.setEnabled(frame.isAdmin());
//        btnEdit.setEnabled(frame.isAdmin());
//        btnDelete.setEnabled(frame.isAdmin());

        btnBack.addActionListener(e -> {
            frame.showPage("home");
        });

        btnAdd.addActionListener(e -> {
            JTextField judul = new JTextField();
            JTextField penulis = new JTextField();
            JTextField tahun = new JTextField();
            
            Object[] input = {
            	"Judul:", judul,
            	"Penulis:", penulis,
            	"Tahun:", tahun
            };
            
//            JOptionPane.showConfirmDialog(this, input, "Tambah Buku", JOptionPane.OK_CANCEL_OPTION);
            int result = JOptionPane.showConfirmDialog(this, input, "Tambah Buku", JOptionPane.OK_CANCEL_OPTION);
            if(result == JOptionPane.OK_OPTION) {
            	Book newBook = new Book(judul.getText(), penulis.getText(), Integer.parseInt(tahun.getText()), false);
            	frame.getBooks().add(newBook);
            	refreshTable(frame.getBooks());
            }
            
        });

        btnEdit.addActionListener(e -> {
            int row = table.getSelectedRow();
            if(row>=0) {
            	Book book = frame.getBooks().get(row);
            	JTextField judul = new JTextField(book.getJudul());
            	JTextField penulis = new JTextField(book.getPenulis());
            	JTextField tahun = new JTextField(Integer.toString(book.getTahun()));
            	
            	Object[] input = {
                    	"Judul:", judul,
                    	"Penulis:", penulis,
                    	"Tahun:", tahun
                    };
            	
            	int result = JOptionPane.showConfirmDialog(this, input, "Edit Buku", JOptionPane.OK_CANCEL_OPTION);
                if(result == JOptionPane.OK_OPTION) {
                	book.setJudul(judul.getText());
                	book.setPenulis(penulis.getText());
                	book.setTahun(Integer.parseInt(tahun.getText()));
                	refreshTable(frame.getBooks());
                }
            	
            } else {
            	JOptionPane.showMessageDialog(this, "Pilih buku yang ingin di edit!");
            };
        });

        btnDelete.addActionListener(e -> {
            int row = table.getSelectedRow();
            if(row>=0) {
            	int confirm = JOptionPane.showConfirmDialog(this, "Yakin ingin menghapus data?", "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);
            	if(confirm == JOptionPane.YES_OPTION) {
            		frame.getBooks().remove(row);
            		refreshTable(frame.getBooks());
            	}
            } else {
            	JOptionPane.showMessageDialog(this, "Pilih buku yang ingin dihapus!");
            }
        });
        
        refreshTable(frame.getBooks());

    }
    private void refreshTable(ArrayList<Book> books) {
        model.setRowCount(0);
        for (Book b : books) {
            model.addRow(new Object[]{b.getJudul(), b.getPenulis(), b.getTahun()});
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
